swagger: '2.0'
info: {title: GetPresences, description: Get presences, version: '1.0'}
host: graph.microsoft.com
basePath: /v1.0
schemes: [https]
consumes: []
produces: []
paths:
  /communications/getPresencesByUserId:
    post:
      responses:
        default:
          description: default
          schema:
            type: object
            properties:
              value:
                type: array
                items:
                  type: object
                  properties:
                    id: {type: string, description: id}
                    availability: {type: string, description: availability}
                    activity: {type: string, description: activity}
                description: value
      summary: getPresencesByUserId
      description: getPresencesByUserId
      operationId: getPresencesByUserId
      x-ms-visibility: important
      parameters:
      - name: body
        in: body
        required: false
        schema:
          type: object
          properties:
            ids:
              type: array
              items: {type: string, description: ids, title: ids}
              description: ids
          required: [ids]
definitions: {}
parameters: {}
responses: {}
securityDefinitions:
  oauth2_auth:
    type: oauth2
    flow: accessCode
    authorizationUrl: https://login.windows.net/common/oauth2/authorize
    tokenUrl: https://login.windows.net/common/oauth2/authorize
    scopes: {'https://graph.microsoft.com/.default': 'https://graph.microsoft.com/.default'}
security:
- oauth2_auth: ['https://graph.microsoft.com/.default']
tags: []
